### ISSUE TITLE
tr 10-open-md and 11-licensing-md 

### ISSUE THREAD

**Issue by orchid00** [carpentries/git-novice-es-archive#10]
Dos episodios cortos asignados a Laura @LauCIFASIS

**Comment by LauCIFASIS** [comment]
Buen dia a todos los Carpentries Latinoamericanos !!

Soy Laura de la Argentina, y hoy me uno al grupo.

A trabajar !!!!

**Comment by LauCIFASIS** [comment]
Hola Paula,
Estoy un poco perdida. 
En github no tengo  "enhancement" del episodio a traducir.
Pude bajar el archivo a traducir del transifex. Mi pregunta es: cuando lo termine de traducir lo subo x transifex ?

L.

**Comment by orchid00** [comment]
Hola Laura, 
Yo tambien estoy usando Transifex por primera vez. Estos son los pasos que yo hice.
1. log in to Transifex
2. Ubica la carpeta de Git-novice-es
3. Busca Resources (ahi se ven todos los episodios de la leccion y te muestra el porcentaje de cada traduccion)
4. dale click en el episodio que te toca traducir
5. En la parte de arriba derecha hay un boton que dice Translate
6. Te aparecen strings para traducir y luego que traduces hacer click en save translation

**Comment by LauCIFASIS** [comment]
Gracias Paula... ya estoy traduciendo el episodio 10.

**Comment by LauCIFASIS** [comment]
Gracias Paula, ya estoy traduciendo :) 

El 10-10-2017 02:40, Paula Andrea escribió:

> Hola Laura,
> Yo tambien estoy usando Transifex por primera vez. Estos son los pasos que yo hice. 
> 
> * log in to Transifex
> * Ubica la carpeta de Git-novice-es
> * Busca Resources (ahi se ven todos los episodios de la leccion y te muestra el porcentaje de cada traduccion)
> * dale click en el episodio que te toca traducir
> * En la parte de arriba derecha hay un boton que dice Translate
> * Te aparecen strings para traducir y luego que traduces hacer click en save translation
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

-- 
Ing. Laura Angelone

FCEIA - UNR 
Pellegrini 250 - Rosario
langelon@fceia.unr.edu.ar

Magister en Informática 
Grupo Bioinformática
Centro Internacional Franco Argentino
de Ciencias de la Información y de Sistemas 
CIFASIS - CONICET
TEL: (+54-341)  4237248 Int. 319

angelone@cifasis-conicet.gov.ar
http://www.cifasis-conicet.gov.ar/ 

Links:
------
[1]
https://github.com/Carpentries-ES/git-novice/issues/10#issuecomment-335366470
[2]

**Comment by LauCIFASIS** [comment]
Hola Paula, 
He leido las últimas noticias de la reunión del 17.
Ahora estamos en github y abandonamos Transifex ... ya me habia gustado :( 

Pregunta: debo empezar nuevamente la traducción en github? o pasan lo habia habia hecho en transifex?
Otra pregunta: como es el proceso aqui en github?

gracias!!
Laura.-

**Comment by orchid00** [comment]
Hola Laura , 

Sí ha sido una pena que vamos a dejar de usar Transifex, a mi también me estaba gustando mucho. He descargado tu traducción y la he movevido al github. Puedes verlas aquí https://github.com/Carpentries-ES/git-novice/tree/gh-pages/_episodes_es @javijevi esta haciendo la revisión de esta lección, pero si tienes tiempo de darle una mirada a los episodios para encontrar algun error ortográfico o algo así, bienvenida. 
Si encuentras algunos términos técnicos en tu traducción o en la de otros, por favor seguir los standards de este documento https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md ponernos en negrita. 

Gracias, estamos en contacto, espero verte en la reunión la próxima semana.

**Comment by LauCIFASIS** [comment]
Hola Paula!!

Ya estoy arrancando  :)

Lo único que no se como poner negrita

**Comment by LauCIFASIS** [comment]
Paula fijate si podés subir a Project1 el episodio 11 que ya está listo. 

Ahora me fijo en la lección completa, si encuentro error ortográfico o semántica que no suene bien.

**Comment by javijevi** [comment]
Hola. ¿Qué quieres decir con "subir a Project1"?

**Comment by javijevi** [comment]
LauCIFASIS, creo que nos debemos poner de acuerdo, porque estamos haciendo trabajo doble (yo he corregido el capítulo 2 y luego no he podido hacer el commit porque entraba en conflicto con los cambios que estás haciendo tú).

**Comment by LauCIFASIS** [comment]
Sorry Javier. Pero Paula me pidio hacer "...la revisión de esta lección, pero si tienes tiempo de darle una mirada a los episodios para encontrar algun error ortográfico o algo así, bienvenida."

.... tampoco quiero duplicar el trabajo ni hacer perder tiempo

**Comment by javijevi** [comment]
Claro, claro, no es ninguna acusación... Es que no es fácil coordinarse... jajajaja... Yo estoy empezando ahora por el final (episodio 14 hacia atrás). Si te parece, sigues tú por el 2 hacia adelante, ok?

**Comment by LauCIFASIS** [comment]
No problem!
 
... sigo el lunes porque ahora tengo que seguir en el trabajo.....buen fin de semana !!!

**Comment by javijevi** [comment]
Sí, yo voy a acabar el 14 y seguiré más tarde. Quedamos así, pues.

Buen finde!!!

**Comment by orchid00** [comment]
Bueno creo que ya se pusieron de acuerdo, me alegra.
@LauCIFASIS negritas se pone entre dos asteriscos ** ** una vez que checkes el 10 y 11 que no le falten tildes, abrir y cerrar preguntas y las negritas para los terminos tecnicos que no traducimos creo que con eso sera suficiente. 
@javijevi puedes saltarte el dos para que o termine laura y seguir con los otros episodios.

**Comment by LauCIFASIS** [comment]
Paula, recien terminé de revisar el 10 y 11. Me parece que están listo :)

Despues sigo con el 2.

Avisame si querés que revise otro.

**Comment by orchid00** [comment]
Muy bien Laura, gracias! 
Si puedes revisar el episodio 2 antes de la reunion seria ideal. Si no puedes hacer esto, solo unete a la reunion y hablaremos del progreso.
Gracias

**Comment by ErinBecker** [comment]
It looks like this episode has been translated. Can this issue be closed?
