### ISSUE TITLE
tr 12-citation-md and 13-hosting-md

### ISSUE THREAD

**Issue by orchid00** [carpentries/git-novice-es-archive#11]
Asignados dos episodios cortos a Hugo

**Comment by HugoGuillen** [comment]
Terminé de traducir y subí los .md a transifex. 
Saludos!

**Comment by orchid00** [comment]
Muy bien!, si estas en la reunion el lunes puedes pedir a alguien que haga los updates en este link: https://github.com/Carpentries-ES/git-novice/projects/1 no tengo permisos, pero seguro Francisco cuando tenga tiempo revisa lo de los permisos.

**Comment by ErinBecker** [comment]
It looks like this episode has been translated. Can this issue be closed?
