### ISSUE TITLE
tr 14-supplemental-rstudio-md

### ISSUE THREAD

**Issue by orchid00** [carpentries/git-novice-es-archive#12]
Episodio 14 asignado a Paula @orchid00

**Comment by orchid00** [comment]
He terminado la traducción. Quisiera que alguien que tenga RStudio  y Git en español pueda revisar mis traducciones, por que no estoy segura si los nombres de comandos como Push Pull commit se mantienen en Ingles o no. @Helysalgado le puedes dar una mirada a este episodio por favor?

**Comment by Helysalgado** [comment]
Ok

**Comment by ErinBecker** [comment]
It looks like this episode has been translated. Can this issue be closed?
